# Basic
title: Michael Dai's Blog
subtitle: 记录生活
welcome_message: <a href="/2018/08/使用说明列表/" target="_blank"></a>
#description: Vno Jekyll is a port of my Ghost theme vno.
#creator: <a href="http://onev.cat">@onevcat</a>

url: "https://michaeldai7.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple

# The blog button should not be removed.
blog_button:
    title: 日志
    description: 查看日志

# Navigation buttons in the front page.
nav:
    - {title: 返回主页, description: Michael Dai的主页, url: 'https://www.michaeldai.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: VPNPro
    # duoshuo: 
    
# Social
social:
    facebook: michealxia7@gmail.com
    github: michaeldai7
    twitter: michealxia7@gmail.com
    gplus: michealxia7@gmail.com
    mail: michealxia7@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true
