name: Michael Dai
permalink: :year/:month/:day/:title
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
# 网站底部的社交信息外链
link:
  email : michealxia7@gmail.com
  github : michaeldai7
  twitter : 
  jianshu: 

# Links in the navigation, you can modify both link name and link url
# 网站顶部的导航链接，支持修改链接名称及链接
nav:
   Home: http://michaeldai.com
   Diary: http://blog.michaeldai.com
   Presentations: 

   
markdown: kramdown
highlighter: rouge