title: Michael Dai's Blog
subtitle: 记录生活
welcome_message: 17岁，是个学生

url: "https://michaeldai7.github.io"

permalink: /:year/:month/:title/

highlighter: rouge

cover_color: purple

blog_button:
    title: 日志
    description: 查看日志

nav:
    - {title: 返回主页, description: Michael Dai的主页, url: 'https://www.michaeldai.com'}

gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

comment:

social:
    facebook: michealxia7@gmail.com
    github: michaeldai7
    twitter: michaeldai15
    gplus: 
    mail: michealxia7@gmail.com


ga:

kramdown:

  parse_block_html: true
